### ISSUE TITLE
Could not establish connection to xud. Retrying in 5 seconds.

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/market-maker-tools#15] opened 2020-06-15 09:15 UTC
I brought up a new simnet environment (containers running), but waited for several hours before I created the environment. Once everything was created and I received coins, arby couldn't connect to xud:
```
2020-06-15 08:38:41.4141 [OpenDEX] warn: Could not establish connection to xud. Retrying in 5 seconds.
2020-06-15 08:38:41.4141 [Centralized] trace: ETHBTC stream closed
2020-06-15 08:38:46.4646 [OpenDEX] warn: Could not establish connection to xud. Retrying in 5 seconds.
2020-06-15 08:38:46.4646 [Centralized] trace: ETHBTC stream closed
simnet > status
┌─────────┬──────────────────────────────────────────────────┐
│ SERVICE │ STATUS                                           │
├─────────┼──────────────────────────────────────────────────┤
│ lndbtc  │ Ready                                            │
├─────────┼──────────────────────────────────────────────────┤
│ lndltc  │ Ready                                            │
├─────────┼──────────────────────────────────────────────────┤
│ connext │ Ready                                            │
├─────────┼──────────────────────────────────────────────────┤
│ arby    │ Ready                                            │
├─────────┼──────────────────────────────────────────────────┤
│ xud     │ Ready                                            │
└─────────┴──────────────────────────────────────────────────┘
```
Then I restarted the whole environment and arby connected fine.

**Comment by kilrau** [comment] 2020-06-15 12:53
Same happened when I started xud -b feat/arby on an existing testnet environment:
```
2020-06-15 12:12:58.5858 [OpenDEX] warn: Could not establish connection to xud. Retrying in 5 seconds.
2020-06-15 12:12:58.5858 [Centralized] trace: ETHBTC stream closed
```

**Comment by raladev** [comment] 2020-06-19 16:33
got it today with 2816c11e87e732a833ab73452f3bbdeee49f9f4a commit. Same case, arby restart fixed the situation.
![Screenshot from 2020-06-19 18-07-05](https://user-images.githubusercontent.com/29906866/85157123-afd99480-b263-11ea-90c7-30236b72886f.png)

Logs:
[utils_noarby_conn.log](https://github.com/ExchangeUnion/market-maker-tools/files/4805739/utils_noarby_conn.log)
[arby_noarby_conn.log](https://github.com/ExchangeUnion/market-maker-tools/files/4805740/arby_noarby_conn.log)
[xud_noarby_conn.log](https://github.com/ExchangeUnion/market-maker-tools/files/4805741/xud_noarby_conn.log)

**Comment by erkarl** [comment] 2020-07-06 15:59
At this point I'm still not sure what's causing it. It seems to reproduce only in xud-docker environment. If you see it with the newer/latest version please attach full logs for arby container.

You should be able to get full logs for a docker container using: `sudo vim $(docker inspect --format='{{.LogPath}}' simnet_arby_1)`

**Comment by raladev** [comment] 2020-07-10 11:29
got it with last commit.
[xud_log_stuck_1.log](https://github.com/ExchangeUnion/market-maker-tools/files/4902844/xud_log_stuck_1.log)
[arbylog_no_conn.log](https://github.com/ExchangeUnion/market-maker-tools/files/4902845/arbylog_no_conn.log)

**Comment by erkarl** [comment] 2020-07-31 09:14
Duplicate of https://github.com/ExchangeUnion/market-maker-tools/issues/57

**Closed by erkarl** 2020-07-31 09:14 UTC
Labels: P2, bug
